import Head from 'next/head'

import { getLayoutWithSidebar } from 'layouts/layoutWithSidebar/LayoutWithSidebar'
import { UsersList } from 'templates/home/UsersList'

export default function Index() {
  return (
    <>
      <Head>
        <title>Inctagram Admin</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />

        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <main className={'w-full'}>
        <UsersList />
      </main>
    </>
  )
}

Index.getLayout = getLayoutWithSidebar
