import Head from 'next/head'

import { getLayoutWithSidebar } from 'layouts'
import { PaymentsList } from 'templates'

export default function PaymentsListPage() {
  return (
    <>
      <Head>
        <title>Inctagram Admin</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />

        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <main className={'w-[100vw] h-[100vh] flex items-center justify-center'}>
        <PaymentsList />
      </main>
    </>
  )
}

PaymentsListPage.getLayout = getLayoutWithSidebar
