import Head from 'next/head'
import { CartesianGrid, XAxis, Legend, LineChart, YAxis, Tooltip, Line } from 'recharts'

import { DatePickerWithRange } from 'shared/ui'

const data = [
  {
    name: 'Page A',
    uv: 4000,
    pv: 2400,
  },
  {
    name: 'Page B',
    uv: 3000,
    pv: 1398,
  },
  {
    name: 'Page C',
    uv: 2000,
    pv: 9800,
  },
  {
    name: 'Page D',
    uv: 2780,
    pv: 3908,
  },
  {
    name: 'Page E',
    uv: 1890,
    pv: 4800,
  },
  {
    name: 'Page F',
    uv: 2390,
    pv: 3800,
  },
  {
    name: 'Page G',
    uv: 3490,
    pv: 4300,
  },
]

const valueFormatter = function (number: number) {
  return '$ ' + new Intl.NumberFormat('us').format(number).toString()
}

export type LineChartByDateProps = {
  colors: {
    first: string
    second: string
  }
  dataKey: {
    first: string
    second: string
  }
  data: {
    name: string
    first: number
    second: number
  }
  onDataChange: () => void
}

const LineChartByDate = (props: LineChartByDateProps) => {
  return (
    <>
      <h3
        className={
          'text-lg font-medium  text-tremor-content-strong dark:text-dark-tremor-content-strong '
        }
      >
        Newsletter revenue over time (USD)
      </h3>
      <DatePickerWithRange />
      {/* <LineChart
        className={'mt-4 h-72  text-tremor-content-strong dark:text-dark-tremor-content-strong'}
        data={chartdata}
        index={'date'}
        yAxisWidth={65}
        categories={['SemiAnalysis', 'The Pragmatic Engineer']}
        colors={['indigo', 'cyan']}
        valueFormatter={valueFormatter}
      /> */}
      <LineChart
        width={730}
        height={250}
        data={data}
        margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
      >
        <XAxis dataKey={'name'} />
        <YAxis />
        <Legend verticalAlign={'top'} />
        <Line type={'monotone'} dataKey={'pv'} stroke={'#FFD073'} dot={false} />
        <Line type={'monotone'} dataKey={'uv'} stroke={'#664400'} dot={false} />
      </LineChart>
    </>
  )
}

export default function Statistics() {
  return (
    <>
      <Head>
        <title>Inctagram Admin</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />

        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <main className={'w-[100vw] h-[100vh] flex items-center justify-center'}>
        <LineChartByDate />
      </main>
    </>
  )
}
