import Head from 'next/head'

import { getLayoutWithSidebar } from 'layouts'
import { Statistics } from 'templates/statistics'

export default function StatisticsPage() {
  return (
    <>
      <Head>
        <title>Inctagram Admin</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />

        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <main className={'w-full h-full flex items-center justify-start'}>
        <Statistics />
      </main>
    </>
  )
}
StatisticsPage.getLayout = getLayoutWithSidebar
